apiVersion: v1
kind: Secret
metadata:
  name: custom-monitoring-grafana-datasource
  namespace: custom-monitoring
stringData:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: "custom-monitoring-datasource"
        type: prometheus
        access: proxy
        url: https://prom.custom-monitoring.svc
        basicAuth: false
        withCredentials: false
        isDefault: true
        jsonData:
            tlsSkipVerify: true
            "httpHeaderName1": "Authorization"
        secureJsonData:
            "httpHeaderValue1": "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJjdXN0b20tbW9uaXRvcmluZyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJwcm9tLXRva2VuLWp4a3I4Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InByb20iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI4MGY2NDg1OC04ZWNiLTExZWEtYTU2NS0wMmU3MjVjY2E2MWEiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6Y3VzdG9tLW1vbml0b3Jpbmc6cHJvbSJ9.KF6XnAApmDobwlZeGbXRAOhTINbPQcjDAFmQQry2CYSCKAAUYC-v_jvv3Za9KY-9JL6Idw_-0q2S9CtTr-tu-kX49CZ6EnRN-VAj_FUjBfBTkB3SPeXuE5S7TnCQHdONOdXHtlAXN1Oh9AJnAET1n5sVSTSdgv5UkVpStVOKdBtosJrLFgyRGP2qzhtY7OkSI6VCA4wOgQJkLVAoCyQIsNVbwVPtuHF9CvJvHCAl8VOpBFBNdyydXwIJkfTRGD0AJwIyCNoTvUiqy2NK39izmppGNgPKCMtD6C7F6MvUGpzF9hKlZWkgJt_twyhdeGzdHq-aatDPmFjL-AUXDNLVtg"
        editable: true
